# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
#   # Automatically fetch Medium follower count
#   - MediumFollowersCountPlugin:
#       username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ShadyElyaski/ios-filter-control
      - DynamicSignal/ios-twitter-text-counter

# Google Analytics tracking id
# google_analytics_id:

# HTML Title
title: "Shady Elyaski's Links"

# Avatar image path
avatar: "./images/ShadyDP.jpg"

# Name section text
name: "@ShadyElyaski"

# Tagline section text
tagline: >-
    An iOS engineer from Egypt 🇪🇬 who also loves Scuba & Freediving, Cycling and spearfishing.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  # - link:
  #     icon: "fa-brands fa-medium"
  #     text: "Tech Blog <span class='link-button-text'>({{vars.MediumFollowersCountPlugin}} Followers)</span>"
  #     url: "https://blog.zhgchg.li"
  #     alt: "ZhgChgLi's Tech Blog"
  #     title: "ZhgChgLi's Tech Blog"
  #     target: "_blank"
  # - link:
  #     icon: "fa-brands fa-medium"
  #     text: "Travelog <span class='link-button-text'>({{vars.MediumFollowersCountPlugin}} Followers)</span>"
  #     url: "https://medium.com/ztravel"
  #     alt: "ZhgChgLi's Travelog"
  #     title: "ZhgChgLi's Travelog"
  #     target: "_blank"
  # - link:
  #     icon: "fa-solid fa-rss"
  #     text: "Website"
  #     url: "https://zhgchg.li/"
  #     alt: "ZhgChgLi's Website"
  #     title: "ZhgChgLi's Website"
  #     target: "_blank"
  # - link:
  #     icon: "fa-brands fa-swift"
  #     text: "ZMarkupParser <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZMarkupParser']}} Stars)</span>"
  #     url: "https://github.com/ZhgChgLi/ZMarkupParser"
  #     alt: "ZMarkupParser is a pure-Swift library that helps you to convert HTML strings to NSAttributedString with customized style and tags."
  #     title: "ZMarkupParser is a pure-Swift library that helps you to convert HTML strings to NSAttributedString with customized style and tags."
  #     target: "_blank"
  # - link:
  #     icon: "fa-brands fa-app-store-ios"
  #     text: "ZReviewTender <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZReviewTender']}} Stars)</span>"
  #     url: "https://github.com/ZhgChgLi/ZReviewTender"
  #     alt: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
  #     title: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
  #     target: "_blank"
  # - link:
  #     icon: "fa-brands fa-markdown"
  #     text: "ZMediumToMarkdown <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZMediumToMarkdown']}} Stars)</span>"
  #     url: "https://github.com/ZhgChgLi/ZMediumToMarkdown"
  #     alt: "ZMediumToMarkdown is a powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format."
  #     title: "ZMediumToMarkdown is a powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format."
  #     target: "_blank"
  - link:
      icon: "fa-solid fa-file"
      text: "Resume"
      url: "https://elyaski.com/ShadyElyaski_CV.pdf"
      alt: "ios-filter-control is an iOS Filter UIControl Subclass. Zero Graphics. Highly Customizable."
      title: "Resume"
      target: "_blank"
  - link:
      icon: "fa-solid fa-mobile-screen-button"
      text: "Mobile Apps Portfolio"
      url: "http://mobileapps.elyaski.com"
      alt: "Shady Elyaski's Mobile Apps Portfolio"
      title: "Mobile Apps Portfolio"
      target: "_blank"
  - link:
      icon: "fa-solid fa-file"
      text: "Resume"
      url: "https://elyaski.com/ShadyElyaski_CV.pdf"
      alt: "ios-filter-control is an iOS Filter UIControl Subclass. Zero Graphics. Highly Customizable."
      title: "Resume"
      target: "_blank"
  - link:
      icon: "fa-brands fa-wordpress"
      text: "Blog"
      url: "http://blog.elyaski.com"
      alt: "Shady Elyaski's Blog"
      title: "Blog"
      target: "_blank"
  - link:
      icon: "fa-brands fa-500px"
      text: "Photography"
      url: "http://photography.elyaski.com"
      alt: "Shady Elyaski's Photography"
      title: "Photography"
      target: "_blank"
  - link:
      icon: "fa-brands fa-wordpress"
      text: "Blog"
      url: "https://blog.elyaski.com"
      alt: "ios-filter-control is an iOS Filter UIControl Subclass. Zero Graphics. Highly Customizable."
      title: "Blog"
      target: "_blank"
  - link:
      icon: "fa-brands fa-github"
      text: "ios-filter-control <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/linkyee']}} Stars)</span>"
      url: "https://github.com/ShadyElyaski/ios-filter-control"
      alt: "ios-filter-control is an iOS Filter UIControl Subclass. Zero Graphics. Highly Customizable."
      title: "ios-filter-control GitHub Page"
      target: "_blank"
   - link:
      icon: "fa-brands fa-github"
      text: "ios-twitter-text-counter <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['DynamicSignal/ios-twitter-text-counter']}} Stars)</span>"
      url: "https://github.com/DynamicSignal/ios-twitter-text-counter"
      alt: "ios-twitter-text-counter is a custom UIControl resembles Twitter's new progress based web UI that represents the number of characters left. It also handles highlighting any extra characters in your UITextView."
      title: "ios-twitter-text-counter GitHub Page"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/ShadyElyaski/"
      title: "Instagram"
      alt: "Shady Elyaski's Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/ShadyElyaski/"
      title: "Facebook"
      alt: "Shady Elyaski's Facebook"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/ShadyElyaski/"
      title: "Shady Elyaski's LinkedIn"
      alt: "Shady Elyaski's LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/ShadyElyaski"
      title: "Shady Elyaski's GitHub"
      alt: "Shady Elyaski's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://twitter.com/ShadyElyaski"
      title: "Shady Elyaski's Twitter"
      alt: "Shady Elyaski's Twitter"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:shady@elyaski.com"
      title: "Email: shady@elyaski.com"
      alt: "shady@elyaski.com"
      target: "_blank"

# Footer text
footer: >
    Hi there! Follow me on GitHub, or stay connected on IG or LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://elyaski.com" target="_blank">Elyaski</a>.
